In [3]:
import numpy as np

In [4]:
a = np.array([[[10,20,30,40],[50,60,70,80]],[[10,20,30,40],[50,60,70,80]]])
a

array([[[10, 20, 30, 40],
        [50, 60, 70, 80]],

       [[10, 20, 30, 40],
        [50, 60, 70, 80]]])

In [5]:
print(a.ndim)

3

In [6]:
a.shape

(2, 2, 4)

In [7]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [8]:
m[1,2]

7

In [9]:
m[-1,-1]

14

In [10]:

m[1,1:3]

array([6, 7])

In [11]:
m[1:,2]

array([ 7, 12])

In [12]:
m[0:2,3:]

array([[3, 4],
       [8, 9]])

In [13]:
m[0:2, -1:-3:-1]

array([[4, 3],
       [9, 8]])

In [14]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [16]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [17]:
y=x[(x%3==0) & (x%4==1)]
y

array([9])

In [18]:
a = np.array([[0,0,0,1,1],[0,0,0,1,1],[0,0,0,1,1]]).astype(float)
b= np.arange(10,160,10).reshape(3,5).astype(float)
c=np.vstack([a,b])
np.vstack([c,c])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [19]:
import random
a=np.random.rand(30).reshape(5,6)
a

array([[0.37226792, 0.37212614, 0.12046963, 0.78330807, 0.2816909 ,
        0.28710454],
       [0.38744989, 0.10181107, 0.6660564 , 0.95003065, 0.55161609,
        0.96719906],
       [0.23644819, 0.73496099, 0.30941097, 0.99869669, 0.72550777,
        0.76128421],
       [0.61724278, 0.56858756, 0.08127209, 0.15359177, 0.48374262,
        0.04873906],
       [0.58014386, 0.15203666, 0.02660213, 0.8470955 , 0.38010507,
        0.99543861]])

In [20]:
a.max()

0.998696688681436

In [21]:
a.sum(axis=1)

array([2.21696721, 3.62416315, 3.76630882, 1.95317588, 2.98142183])

In [22]:
a.max(axis=1)

array([0.78330807, 0.96719906, 0.99869669, 0.61724278, 0.99543861])

In [23]:
a.mean(axis=0)

array([0.43871053, 0.38590448, 0.24076224, 0.74654454, 0.48453249,
       0.61195309])

In [24]:
a.min(axis=0)

array([0.23644819, 0.10181107, 0.02660213, 0.15359177, 0.2816909 ,
       0.04873906])

In [25]:
a=np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
a.astype(int)

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [26]:
a[1].argsort()

array([0, 3, 1, 2])

In [27]:
a[0][a[1].argsort()]

array([1, 4, 2, 3])

In [28]:
a[2][a[1].argsort()]

array([ 81, 100,  59,  90])

In [29]:
c = np.array([a[0][a[1].argsort()], a[1], a[2][a[1].argsort()]])
c

array([[  1,   4,   2,   3],
       [ 46,  99, 100,  71],
       [ 81, 100,  59,  90]])

In [30]:

np.random.randint(1,100,10)

array([62, 18, 55, 68,  1, 59, 53, 49, 43, 75])

In [31]:
import random
random.seed(2021)
a = np.random.randint(1,100,10)
for i in a:
  if i % 2 == 0:
    print('1')
  elif i % 2 ==1 :
    print('0')

0
1
0
1
1
1
0
1
1
1

In [97]:
import random
b=0
for i in range(1,101):
  a = np.random.randint(1,7,1)
  b += a
  print(b/i)

[2.]
[2.5]
[3.]
[2.75]
[3.2]
[3.33333333]
[3.14285714]
[3.375]
[3.11111111]
[3.2]
[3.09090909]
[2.91666667]
[2.84615385]
[2.71428571]
[2.6]
[2.625]
[2.58823529]
[2.66666667]
[2.68421053]
[2.8]
[2.85714286]
[2.86363636]
[2.82608696]
[2.75]
[2.88]
[2.92307692]
[2.96296296]
[3.]
[3.06896552]
[3.1]
[3.09677419]
[3.0625]
[3.06060606]
[3.05882353]
[3.05714286]
[3.]
[3.05405405]
[3.13157895]
[3.17948718]
[3.25]
[3.19512195]
[3.14285714]
[3.20930233]
[3.20454545]
[3.26666667]
[3.2826087]
[3.34042553]
[3.39583333]
[3.36734694]
[3.42]
[3.39215686]
[3.36538462]
[3.32075472]
[3.27777778]
[3.25454545]
[3.25]
[3.21052632]
[3.22413793]
[3.25423729]
[3.23333333]
[3.21311475]
[3.19354839]
[3.20634921]
[3.21875]
[3.2]
[3.22727273]
[3.23880597]
[3.25]
[3.26086957]
[3.3]
[3.32394366]
[3.33333333]
[3.32876712]
[3.33783784]
[3.33333333]
[3.30263158]
[3.27272727]
[3.29487179]
[3.32911392]
[3.3375]
[3.32098765]
[3.30487805]
[3.28915663]
[3.27380952]
[3.29411765]
[3.27906977]
[3.31034483]
[3.30681818]
[3.29213483]
[3.31111111]
[3.32967033]
[3.34782609]
[3.37634409]
[3.40425532]
[3.37894737]
[3.40625]
[3.3814433]
[3.37755102]
[3.38383838]
[3.38]

In [37]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()

In [95]:
df = pd.DataFrame(iris.data, columns= iris.feature_names)
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [75]:
a=iris.target_names

'ver'

In [88]:
name1=a[0][:3].upper()
name2=a[1][:3].upper()
name3=a[2][:3].upper()

In [91]:
for i in range(3):
  name = a[i][:3].upper()
  print(name)

SET
VER
VIR

In [104]:
a= pd.Series([1,3,4,5,6], index = ('d','f','r','y','q'))
b= pd.Series([2,6,4,0,1], index = ('d','f','c','v','b'))
c=a+b
c[c.notnull()]

d    3.0
f    9.0
dtype: float64

In [110]:
df = pd.DataFrame([[1,'T',4.0,5,6],[2,'d',4.0,5,6],[2,'q',4.0,5,6],[4,'v',6.0,7,8],[0,'j',8.0,7,6]], columns = ['아리가또','땡큐','쒜쒜','감사','쿠텐탁'])
df

   아리가또 땡큐   쒜쒜  감사  쿠텐탁
0     1  T  4.0   5    6
1     2  d  4.0   5    6
2     2  q  4.0   5    6
3     4  v  6.0   7    8
4     0  j  8.0   7    6

In [111]:
df.T

      0  1  2  3  4
아리가또  1  2  2  4  0
땡큐    T  d  q  v  j
쒜쒜    4  4  4  6  8
감사    5  5  5  7  7
쿠텐탁   6  6  6  8  6

In [112]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)

In [123]:
df['평균'] = df.mean(axis=1)
df

    국어  영어  수학         평균
춘향  80  90  90  86.666667
몽룡  90  70  60  73.333333
향단  70  60  80  70.000000
방자  30  40  70  46.666667

In [129]:
df.loc['방자','영어'] = 80
df['평균'] = df.mean(axis=1)
df

    국어  영어  수학         평균
춘향  80  90  90  86.666667
몽룡  90  70  60  73.333333
향단  70  60  80  70.000000
방자  30  80  70  59.791667

In [130]:
df['춘향':'춘향']

    국어  영어  수학         평균
춘향  80  90  90  86.666667

In [134]:
df.loc['향단',:]

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64

In [8]:
import random
import numpy as np
import pandas as pd
a= np.random.randint(1,100,25).reshape(5,5)
df = pd.DataFrame(a, columns=['야바','리','욜','열','헐'], index= ['1','2','3','4','5'])
df

   야바   리   욜   열   헐
1  88  29  99  84  98
2  79  77  65  88   9
3   5  30  11  89  54
4  15  84  50  26  65
5  34  59  66  26  13

In [15]:
df['야바'] #1
df.loc['2':,['욜']] #2

    욜
2  65
3  11
4  50
5  66

In [21]:
import seaborn as sns
titanic = sns.load_dataset("titanic")
titanic.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [25]:
titanic.groupby('sex').count()

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
sex,,,,,,,,,,,,,,
female,314,314,261,314,314,314,312,314,314,314,97,312,314,314
male,577,577,453,577,577,577,577,577,577,577,106,577,577,577

In [52]:
titanic[titanic.sex == 'female']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [63]:
a=titanic.sort_values(by='sex')
a.loc[:,'sex'].value_counts()

male      577
female    314
Name: sex, dtype: int64

In [66]:
a=titanic.sort_values(by='age').loc[:,'age'].value_counts()
a

24.00    30
22.00    27
18.00    26
19.00    25
30.00    25
         ..
36.50     1
74.00     1
0.92      1
70.50     1
12.00     1
Name: age, Length: 88, dtype: int64

In [68]:
titanic.age.mean()

29.69911764705882

In [72]:
titanic[titanic.sex=='female'].age.mean()

27.915708812260537

In [75]:
titanic[(titanic.pclass==1) &(titanic.sex=='female')].age.mean()

34.61176470588235

In [76]:
## apply 부터 복습